config/routes.rb
Crowdzorg::Application.routes.draw do

  match "over-ons" => "pages#about"

  match "contact" => "pages#contact"

  resources :reviews

  resources :comments

  resources :categories

  match "opdrachten/aanmaken" => "tasks#new"

  resources :opdrachten, :controller => "tasks", :as => "tasks"

  match "hulpverleners" => "users#index"
  

  devise_for :users
  resources :users, :only => [:index, :show]

  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_search-widget.html.erb
	<div class="twelve columns hide-on-phones">
		<div class="search-widget panel">
			<h3>Maak een keuze</h3>
			<ul class="unstyled home">
				<li>
					<a href="#" class="left1">
						<div class="widget-button">
							<h4>Ik zoek Hulp</h4>
							<%= image_tag("arrow-left-white.png", :class => "arrow-left") %>
							<h6>Bent u opzoek naar iemand die u te hulp kan schieten? Klik dan hier!</h6>
						</div>
					</a>
					<ul class="go-left1">
					 	<li>
					 		<a href="#" class="left2">
						 		<div class="widget-button level2">
									<h4>Ik zoek Hulp</h4>
									<%= image_tag("arrow-left-white.png", :class => "arrow-left") %>
									<h5>Zoeken naar Hulpverleners</h5>
									<p>Bent u opzoek naar iemand die u hulp kan bieden? Klik hier om direct naar hulpverleners.</p>
								</div>
					 		</a>
					 		<ul class="go-left2">
					 			<li>
					 				<%= link_to(users_path) do %>
							 		<div class="widget-button level3">
										<h4>Ik zoek Hulp</h4>
										<h5>Zoeken naar Hulpverleners</h5>
										<p>Klik hier om hulpverleners te zoeken op basis van hun naam.</p>
									</div>
									<% end %>
					 			</li>
					 			<li>
					 				<%= link_to(users_path) do %>
							 		<div class="widget-button level3">
										<h4>Ik zoek Hulp</h4>
										<h5>Zoeken naar Hulpverleners</h5>
										<p>Klik hier om hulpverleners te zoeken op basis van hun locatie.</p>
									</div>
									<% end %>
					 			</li>
					 			<a href="#" class="nice small radius blue button left2-back">Terug</a>
					 		</ul>
					 	</li>
					 	<li>
					 		<a href="#" class="left2">
								<div class="widget-button level2">
									<h4>Ik zoek Hulp</h4>
									<%= image_tag("arrow-left-white.png", :class => "arrow-left") %>
									<h5>Een Opdracht Aanmaken</h5>
									<p>Wilt u uw eigen opdracht aanmaken, zodat hulpverleners hier op kunnen reargeren? Klik dan hier.</p>
								</div>
					 		</a>
					 		<ul class="go-left2">
					 			<li>
					 				<%= link_to(tasks_path) do %>
									<div class="widget-button level3">
										<h4>Ik zoek Hulp</h4>
										<h6>Opdrachten bekijken</h6>
										<p>Weet u niet meer precies hoe het moet? Bekijk hier het overzicht van de opdrachten.</p>
									</div>
									<% end %>
								</li>
								<li>
									<%= link_to(new_task_path) do %>
									<div class="widget-button level3">
										<h4>Ik zoek Hulp</h4>
										<h6>Een Opdracht Aanmaken</h6>
										<p>Klik hier om een eigen project aan te maken.</p>
									</div>
									<% end %>
								</li>
					 			<a href="#" class="nice small radius blue button left2-back">Terug</a>
					 		</ul>
					 	</li>
					 	<a href="#" class="nice small radius blue button left1-back">Terug</a>
					</ul>
				</li>
				<li>
					<a href="#" class="right1">
						<div class="widget-button">
							<h4>Ik bied Hulp</h4>
							<%= image_tag("arrow-right-white.png", :class => "arrow-right") %>
							<h6>Wilt u uwzelf aanbieden? Klik dan hier!</h6>
						</div>
					</a>
					<ul class="go-right1">
					 	<li>
					 		<a href="#" class="right2">
								<div class="widget-button level2">
									<h4>Ik bied Hulp</h4>
									<%= image_tag("arrow-right-white.png", :class => "arrow-right") %>
									<h5>Zoeken naar Opdrachten</h5>
									<p>Bent u op zoek naar een opdracht? Klik hier om meteen te zoeken naar openstaande opdrachten.</p>
								</div>
					 		</a>
					 		<ul class="go-right2">
					 			<li>
					 				<%= link_to(tasks_path) do %>
									<div class="widget-button level3">
										<h4>Ik bied Hulp</h4>
										<h5>Zoeken naar Opdrachten</h5>
										<p>Klik hier om opdrachten te zoeken op basis van hun naam.</p>
									</div>
									<% end %>
					 			</li>
					 			<li>
					 				<%= link_to(tasks_path) do %>
									<div class="widget-button level3">
										<h4>Ik bied Hulp</h4>
										<h5>Zoeken naar Opdrachten</h5>
										<p>Klik hier om opdrachten te zoeken op basis van hun locatie.</p>
									</div>
									<% end %>
					 			</li>
					 			<a href="#" class="nice small radius blue button right2-back">Terug</a>
					 		</ul>
					 	</li>
					 	<li>
					 		<a href="#" class="right2">
								<div class="widget-button level2">
									<h4>Ik bied Hulp</h4>
									<%= image_tag("arrow-right-white.png", :class => "arrow-right") %>
									<h5>Mezelf aanbieden</h5>
									<p>U wilt uzelf aanbieden om hulp te verlenen? Klik dan hier</p>
								</div>
					 		</a>
					 		<ul class="go-right2">
					 			<li>
					 				<%= link_to(new_user_registration_path) do %>
									<div class="widget-button level3">
										<h4>Ik bied Hulp</h4>
										<h5>Mezelf aanbieden</h5>
										<p>Ik ben een professional</p>
									</div>
									<% end %>
					 			</li>
					 			<li>
					 				<%= link_to(new_user_registration_path) do %>
									<div class="widget-button level3">
										<h4>Ik bied Hulp</h4>
										<h5>Mezelf aanbieden</h5>
										<p>Ik ben een vrijwilliger</p>
									</div>
									<% end %>
					 			</li>
					 			<a href="#" class="nice small radius blue button right2-back">Terug</a>
					 		</ul>
					 	</li>
					 	<a href="#" class="nice small radius blue button right1-back">Terug</a>
					</ul>
				</li>
			</ul>
		</div>
	</div>

app/views/home/index.html.erb
<%= render 'home/search-widget'%>
<div class="row"><div class="six columns centered center-on-phones"><h2>Hoe werkt Crowdzorg?</h2></div>
<div class="row">
	<div class="ten columns centered">
		<div class="stappen">
		<h3>Stap 1</h3>
		<p><em>"Plaats geheel vrijblijvend een opdracht of meld u aan als hulpverlener"</em></p>
		</div>
		<div class="stappen">
		<h3>Stap 2</h3>
		<p><em>"Uw opdracht wordt bekeken door hulpverleners en hopelijk ontstaat er een match"</em></p>
		</div>
		<div class="stappen">
		<h3>Stap 3</h3>
		<p><em>"Als er een match is gevonden resulteerd dit hopelijk een een succesvol voltooide opdracht!"</em></p>
		</div>
	</div>
</div>