config/routes.rb
Crowdzorg::Application.routes.draw do

  match "over-ons" => "pages#about"

  match "contact" => "pages#contact"

  resources :reviews

  resources :comments

  resources :categories

  match "opdrachten/aanmaken" => "tasks#new"

  resources :opdrachten, :controller => "tasks", :as => "tasks"

  match "hulpverleners" => "users#index"
  

  devise_for :users
  resources :users, :only => [:index, :show]

  root :to => "home#index"

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :ok }
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :helpfull %><br />
    <%= f.text_field :helpfull %>
  </div>
  <div class="field">
    <%= f.label :social %><br />
    <%= f.text_field :social %>
  </div>
  <div class="field">
    <%= f.label :dedication %><br />
    <%= f.text_field :dedication %>
  </div>
  <div class="field">
    <%= f.label :accessibility %><br />
    <%= f.text_field :accessibility %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :taks_id %><br />
    <%= f.text_field :taks_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Helpfull</th>
    <th>Social</th>
    <th>Dedication</th>
    <th>Accessibility</th>
    <th>Content</th>
    <th>Taks</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.helpfull %></td>
    <td><%= review.social %></td>
    <td><%= review.dedication %></td>
    <td><%= review.accessibility %></td>
    <td><%= review.content %></td>
    <td><%= review.taks_id %></td>
    <td><%= review.user_id %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Helpfull:</b>
  <%= @review.helpfull %>
</p>

<p>
  <b>Social:</b>
  <%= @review.social %>
</p>

<p>
  <b>Dedication:</b>
  <%= @review.dedication %>
</p>

<p>
  <b>Accessibility:</b>
  <%= @review.accessibility %>
</p>

<p>
  <b>Content:</b>
  <%= @review.content %>
</p>

<p>
  <b>Taks:</b>
  <%= @review.taks_id %>
</p>

<p>
  <b>User:</b>
  <%= @review.user_id %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>